### PR TITLE
feat: Add uikitcatalog for iOS 13 (bundle id is same as ui catalog)

### PR DESCRIPTION
**Pull request by KazuCocoa**
[update]

- For Xcode 10- env => Build ui-catalog which is same as previous app
    - `npm run install` (Build existing ui-category)
- For Xcode 11+ env => vBuilds uikit-catalog which is new one for Xcode 11+ and iOS13+ env
    - `npm run install:ios13`

Currently, I created two directories, `UICatalog` and `UIKitCatalog` for Xcode 10- and Xcode 11+. Because we should remain UICataglo until Xcode 10 will be expired from our support.

----
----

[original]

Current ios-uicatalog returns wrong coordinates only on iOS 13. It did not happen the combination of Xcode 11 x iOS 12.
https://gist.github.com/KazuCocoa/e5ed3b266da87c68882379ba2c02c2ef

I guess this is because of safeArea or something new features in iOS 13.

It did not happen when I applied the latest UIKit catalog sample code.
But the latest one can not build with Xcode 10.x. It is only for Xcode 11 and iOS 13+ since the sample uses some new methods for iOS 13.

----

- Replaced ui-cataglog to the latest one: https://developer.apple.com/documentation/uikit/views_and_controls/uikit_catalog_creating_and_customizing_views_and_controls
    - Change the bundle id to `com.example.apple-samplecode.UICatalog` not to break our existing tests handling bundle id of ui-catalog
    - Rename to `UICatalog-xxxx` from `UIKitCatalog-xxx` in `build/` directory as a result of `npm run build`

---

https://github.com/appium/ios-uicatalog/compare/upgrade-uicatalog?expand=1#diff-60b1ea008fb73ffbae2cf87986568343

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
The CI is not very happy though

**Comment by umutuzgur** [comment]
I can run the appium-xcuitest-driver tests again with iOS 13 when this is merged. They won't pass until we merge this

**Comment by umutuzgur** [comment]
@KazuCocoa Is there something wrong with the directories? It seems like all the files moved from `UICatalog` folder to `UICatalog/UICatalog` folder

**Comment by KazuCocoa** [comment]
changed to WIP and updated https://github.com/appium/ios-uicatalog/pull/15#issue-308335290
(Tweaking travis build now)

**Comment by umutuzgur** [comment]
@KazuCocoa Is there anything else to be done or can we merge it now?

**Comment by KazuCocoa** [comment]
We can merge this if https://github.com/appium/ios-uicatalog/pull/15#issue-308335290's updated way is good for now.
(I just updated readme about `install:ios13` command)

**Comment by KazuCocoa** [comment]
will merge this.
We can build existing ui-catalog as `npm install`. The output is in UICatalog directory.
`npm run install:ios13` is for iOS 13 x Xcode 11.

**Pull request merged**
